stages:
  - build

build-ubuntu:
  stage: build
  image: registry.gitlab.com/nxxm/nxxm/ci/ubuntu-cpp:latest
  script:
    - mkdir build/ && cd build/ && cmake .. && cmake --build .

build-macos:
  stage: build
  tags:
    - macOS
  script:
    - mkdir build/ && cd build/ && cmake .. && cmake --build .

build-win:
  stage: build
  tags:
    - win10
  script:
    - set PreferredToolArchitecture=x64
    - mkdir build && cd build && cmake .. && cmake --build .
